language: node_js
version: 1.0
sudo: false
node_js:
  - 10
install:
  - npm install
script:
  - npm run lint
  - npm run build
deploy:
  edge: true
  provider: npm
  email: "--"
  api_key: "--"
  skip_cleanup: true
  on:
    branch: master
