# Should run on each push, this should include pull requests
#
# If the commit message starts with "skip:build" we will skip this action
#

name: Build

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    if: startsWith(github.event.head_commit.message, "skip:build") == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
